package de.blinkenlights.bmix.mixer;

import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;

/**
 * This class is a viewport to an image source used for creating outputs
 * from the main mixdown buffer.
 */
public class BLImageViewport implements BLImage {
    private final BLImage source;
    private final BufferedImage sourceImage;
    private final Rectangle viewport;

    /**
     * Bits per pixel for {@link #getNetworkBytes()}. Must be 4 or 8.
     */
    private final int bpp;

    /**
     * Creates a new BLImageViewport
     * 
     * @param source
     *            the source image to use
     * @param viewport
     *            the Rectangle specifying the rectangle for this viewport
     * @param bpp
     *            the number of bits per pixel in the network data generated by
     *            {@link #getNetworkBytes()}. Only makes sense when this is a viewport
     *            of a MCU_MULTIFRAME output. Valid values are 4 and 8.
     */
    public BLImageViewport(BLImage source, Rectangle viewport, int bpp) {
        this.source = source;
        this.sourceImage = new BufferedImage(source.getImageWidth(), source.getImageHeight(), BufferedImage.TYPE_INT_ARGB);
        this.viewport = viewport;
        this.bpp = bpp;
        checkBPP(bpp);
    }

    private void checkBPP(int bpp) {
        if (bpp != 4 && bpp != 8) {
            throw new IllegalArgumentException("Bad bpp value: " + bpp + " (expected 4 or 8)");
        }
    }

    /**
     * Fills bi with the cropped version of the image this viewport wraps.
     */
    public void fillBufferedImage(BufferedImage bi) {
        source.fillBufferedImage(sourceImage);
        Graphics2D big = bi.createGraphics();
        big.drawImage(
                sourceImage,
                0, 0, viewport.width, viewport.height,
                viewport.x, viewport.y, viewport.x + viewport.width, viewport.y + viewport.height,
                null);
        big.dispose();
    }

    /**
     * Returns the viewport's height.
     */
    public int getImageHeight() {
        return viewport.height;
    }

    /**
     * Returns the viewport's width.
     */
    public int getImageWidth() {
        return viewport.width;
    }
    
    /**
     * Returns a copy of this viewport's geometry.
     */
    public Rectangle getViewport() {
		return new Rectangle(viewport);
	}
    
    /**
     * Returns the number of bits per pixel this viewport should have
     * when being sent via MCU_MULTIFRAME packets.
     */
    public int getBpp() {
        return bpp;
    }

	@Override
    public String toString() {
        return "viewport " + viewport;
    }
}
