/* 
 * This file is part of BMix.
 *
 *    BMix is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 * 
 *    BMix is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with BMix.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */


package de.blinkenlights.bmix.main;


/**
 * Exception to wrap multiple errors generated by BMovie classes.
 * 
 * @author dfraser
 *
 */
@SuppressWarnings("serial")
public class BMovieException extends Exception {
	public BMovieException(Throwable cause) {
		super(cause);
	}
}
