package de.blinkenlights.bmix.main;


/**
 * Exception to wrap multiple errors generated by BMovie classes.
 * 
 * @author dfraser
 *
 */
public class BMovieException extends Exception {

	public BMovieException(Throwable cause) {
		super(cause);
	}

	
}
